### ISSUE TITLE
Stone theme not working

### ISSUE THREAD

**Issue by theopfr** [upsided/Upsided-OGS-Themes#1]
Hey, I installed the userscript and tried it out, but it seems like only the board changed.
Here is an image (the stones are the default OGS stones):
![image](https://user-images.githubusercontent.com/25230234/154063525-899bca2f-36b1-4909-b6c1-8f7fce26f3c6.png)

**Comment by upsided** [comment]
I've changed the code so that it forces a redraw in a more direct way. Could someone with this issue test whether it helps? I can't duplicate the problem.

**Comment by theopfr** [comment]
@upsided works now :)
